export type DishCategory = 'Starters' | 'Mains' | 'Breads' | 'Rice' | 'Desserts' | 'Drinks'
export type DishRegion = 'North' | 'South' | 'East' | 'West'

export type ExtendedDish = {
  id: string
  name: string
  hindi: string
  description: string
  price: number
  rating: number
  time: string
  veg: boolean
  image: string
  category: DishCategory
  region: DishRegion
}

export const allDishes: ExtendedDish[] = [
  // ── North ──────────────────────────────────────────────
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    hindi: 'मक्खन चिकन',
    description: 'Tandoor-charred chicken folded into a silky tomato-makhani gravy.',
    price: 329,
    rating: 4.8,
    time: '25 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'North',
  },
  {
    id: 'paneer-tikka-masala',
    name: 'Paneer Tikka Masala',
    hindi: 'पनीर टिक्का',
    description: 'Smoky paneer cubes in a spiced onion-tomato masala.',
    price: 289,
    rating: 4.7,
    time: '20 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'North',
  },
  {
    id: 'chole-bhature',
    name: 'Chole Bhature',
    hindi: 'छोले भटूरे',
    description: 'Amritsari chole with pillowy fried bhature and pickled onions.',
    price: 199,
    rating: 4.6,
    time: '20 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'North',
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    hindi: 'दाल मखनी',
    description: 'Black lentils simmered overnight with butter, cream, and tomato.',
    price: 249,
    rating: 4.8,
    time: '25 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'North',
  },
  {
    id: 'rogan-josh',
    name: 'Rogan Josh',
    hindi: 'रोगन जोश',
    description: 'Kashmiri lamb curry perfumed with fennel, ginger, and ratan jot.',
    price: 379,
    rating: 4.7,
    time: '30 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'North',
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    hindi: 'बटर नान',
    description: 'Soft tandoor-baked flatbread brushed with melted butter.',
    price: 59,
    rating: 4.5,
    time: '10 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=640&h=480&fit=crop',
    category: 'Breads',
    region: 'North',
  },
  {
    id: 'amritsari-kulcha',
    name: 'Amritsari Kulcha',
    hindi: 'अमृतसरी कुलचा',
    description: 'Stuffed potato kulcha with tangy amritsari chole on the side.',
    price: 169,
    rating: 4.6,
    time: '15 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1600628421060-939639517883?w=640&h=480&fit=crop',
    category: 'Breads',
    region: 'North',
  },

  // ── South ──────────────────────────────────────────────
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    hindi: 'मसाला डोसा',
    description: 'Crisp fermented crepe with spiced potato, sambar, and two chutneys.',
    price: 179,
    rating: 4.8,
    time: '15 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'South',
  },
  {
    id: 'chettinad-chicken',
    name: 'Chettinad Chicken',
    hindi: 'चेट्टिनाड चिकन',
    description: 'Fiery Tamil Nadu chicken with freshly ground spices and curry leaves.',
    price: 339,
    rating: 4.7,
    time: '25 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1610057099443-fde6c99db9e1?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'South',
  },
  {
    id: 'appam-stew',
    name: 'Appam & Stew',
    hindi: 'अप्पम और स्टू',
    description: 'Lacey rice hoppers with fragrant Kerala vegetable coconut stew.',
    price: 219,
    rating: 4.6,
    time: '20 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'South',
  },
  {
    id: 'filter-coffee',
    name: 'Filter Coffee',
    hindi: 'फ़िल्टर कॉफ़ी',
    description: 'Strong decoction coffee frothed with boiled milk, served in a davara-tumbler.',
    price: 79,
    rating: 4.9,
    time: '5 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=640&h=480&fit=crop',
    category: 'Drinks',
    region: 'South',
  },
  {
    id: 'medu-vada',
    name: 'Medu Vada',
    hindi: 'मेदु वड़ा',
    description: 'Crispy urad dal doughnuts served with sambar and coconut chutney.',
    price: 129,
    rating: 4.5,
    time: '12 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=640&h=480&fit=crop',
    category: 'Starters',
    region: 'South',
  },

  // ── East ───────────────────────────────────────────────
  {
    id: 'kosha-mangsho',
    name: 'Kosha Mangsho',
    hindi: 'कोशा मांसो',
    description: 'Bengali slow-cooked mutton in a rich onion and whole-spice gravy.',
    price: 399,
    rating: 4.8,
    time: '35 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'East',
  },
  {
    id: 'machher-jhol',
    name: 'Machher Jhol',
    hindi: 'माछेर झोल',
    description: 'Light Bengali fish curry with potatoes, tomato, and nigella seeds.',
    price: 299,
    rating: 4.6,
    time: '25 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1626500155537-45a982d40497?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'East',
  },
  {
    id: 'momos',
    name: 'Steamed Momos',
    hindi: 'मोमोज़',
    description: 'Tibetan-style dumplings stuffed with veggies, served with fiery red chutney.',
    price: 159,
    rating: 4.7,
    time: '15 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=640&h=480&fit=crop',
    category: 'Starters',
    region: 'East',
  },
  {
    id: 'rasgulla',
    name: 'Rasgulla',
    hindi: 'रसगुल्ला',
    description: 'Spongy chenna balls soaked in light cardamom-scented sugar syrup.',
    price: 99,
    rating: 4.5,
    time: '5 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1666190094762-79e0be58c4ad?w=640&h=480&fit=crop',
    category: 'Desserts',
    region: 'East',
  },

  // ── West ───────────────────────────────────────────────
  {
    id: 'hyderabadi-biryani',
    name: 'Hyderabadi Biryani',
    hindi: 'बिरयानी',
    description: 'Dum-cooked basmati layered with saffron, mint, and slow-braised meat.',
    price: 349,
    rating: 4.9,
    time: '30 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=640&h=480&fit=crop',
    category: 'Rice',
    region: 'West',
  },
  {
    id: 'pav-bhaji',
    name: 'Pav Bhaji',
    hindi: 'पाव भाजी',
    description: 'Mumbai street-style mashed veggie curry with buttery toasted pav.',
    price: 179,
    rating: 4.7,
    time: '15 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'West',
  },
  {
    id: 'vada-pav',
    name: 'Vada Pav',
    hindi: 'वड़ा पाव',
    description: 'Spicy potato fritter in a soft bun with garlic and tamarind chutneys.',
    price: 69,
    rating: 4.6,
    time: '10 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1606491048802-8342506d6471?w=640&h=480&fit=crop',
    category: 'Starters',
    region: 'West',
  },
  {
    id: 'goan-fish-curry',
    name: 'Goan Fish Curry',
    hindi: 'गोवन फिश करी',
    description: 'Coconut and kokum-soured curry with fresh kingfish, served with rice.',
    price: 359,
    rating: 4.8,
    time: '25 min',
    veg: false,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=640&h=480&fit=crop',
    category: 'Mains',
    region: 'West',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    hindi: 'गुलाब जामुन',
    description: 'Golden fried milk-solid dumplings drenched in rose-cardamom syrup.',
    price: 109,
    rating: 4.7,
    time: '5 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1666190094762-79e0be58c4ad?w=640&h=480&fit=crop&q=80',
    category: 'Desserts',
    region: 'West',
  },
  {
    id: 'masala-chai',
    name: 'Masala Chai',
    hindi: 'मसाला चाय',
    description: 'Cutting chai brewed with ginger, cardamom, cloves, and full-fat milk.',
    price: 49,
    rating: 4.8,
    time: '5 min',
    veg: true,
    image: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=640&h=480&fit=crop',
    category: 'Drinks',
    region: 'West',
  },
]

export const categories: DishCategory[] = ['Starters', 'Mains', 'Breads', 'Rice', 'Desserts', 'Drinks']
export const dishRegions: DishRegion[] = ['North', 'South', 'East', 'West']
